CREATE TABLE pessoa (
   nome VARCHAR(100) NOT NULL,
   cpf VARCHAR(100) NOT NULL,
   idade INT NOT NULL,
   sexo VARCHAR(100) NOT NULL,
   senha VARCHAR(100) NOT NULL,
   PRIMARY KEY (cpf) 
);

CREATE TABLE livro (
   id INT NOT NULL,
   nome VARCHAR(100) NOT NULL,
   autor VARCHAR(100) NOT NULL,
   ano_lancamento INT NOT NULL,
   
  
   cpf_pessoa VARCHAR(100) NOT NULL
);

ALTER TABLE LIVRO
ADD FOREIGN KEY (CPF_PESSOA) 
REFERENCES PESSOA(CPF);

CREATE SEQUENCE S_LIVRO 
	MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 ;